# Generated by Django 4.1.3 on 2022-12-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_title_user_bio_user_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grad_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.AddField(
            model_name='user',
            name='National_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], default='Senior', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
