# Generated by Django 4.1.3 on 2022-12-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0003_alter_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
