# Generated by Django 4.1.3 on 2022-12-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0004_remove_profile_bio_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.IntegerField(blank=True, default=2000),
        ),
    ]
